spring.application.name=ECommerce-Web
server.port=8081

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Product_List
spring.datasource.username=root
spring.datasource.password=OneKartLocal!2026

#To create Table or Update it automatically by JPA (Must for MySql Database)
#spring.jpa.hiberbate.ddl-auto = update

#Shows sql query run by JPA in the console
#spring.jpa.show-sql = true
